import { PostCardItemSchema } from '@/types/schema';

export const fakePostCardItems: PostCardItemSchema[] = [
  {
    projectId: 1,
    logoImageUrl: 'https://picsum.photos/id/237/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/217/100/100',
    title: '초등학교 1학년 덧셈과 뺄셈 문제',
    point: 250,
    targetJob: 'ALL',
    questionCount: 8,
  },
  {
    projectId: 2,
    logoImageUrl: 'https://picsum.photos/id/238/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/218/100/100',
    title: '영어 알파벳 대소문자 구별하기 글자수를 넘어가는지 테스트 테스트',
    point: 200,
    targetJob: 'DESIGNER',
    questionCount: 12,
  },
  {
    projectId: 3,
    logoImageUrl: 'https://picsum.photos/id/239/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/219/100/100',
    title: '기초 한자 퀴즈 - 숫자편',
    point: 350,
    targetJob: 'PLANNER',
    questionCount: 10,
  },
  {
    projectId: 4,
    logoImageUrl: 'https://picsum.photos/id/240/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/240/100/100',
    title: '과학 실험 안전수칙 배우기',
    point: 200,
    targetJob: 'DEVELOPER',
    questionCount: 6,
  },
  {
    projectId: 5,
    logoImageUrl: 'https://picsum.photos/id/241/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/241/100/100',
    title: '동물의 생태계 이해하기',
    point: 400,
    targetJob: 'ALL',
    questionCount: 15,
  },
  {
    projectId: 6,
    logoImageUrl: 'https://picsum.photos/id/242/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/242/100/100',
    title: '기초 음악 기호 알아보기',
    point: 280,
    targetJob: 'ALL',
    questionCount: 9,
  },
  {
    projectId: 7,
    logoImageUrl: 'https://picsum.photos/id/243/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/243/100/100',
    title: '우리나라 지도 퍼즐',
    point: 320,
    targetJob: 'DEVELOPER',
    questionCount: 8,
  },
  {
    projectId: 8,
    logoImageUrl: 'https://picsum.photos/id/244/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/244/100/100',
    title: '기초 영단어 맞추기',
    point: 300,
    targetJob: 'ALL',
    questionCount: 12,
  },
  {
    projectId: 9,
    logoImageUrl: 'https://picsum.photos/id/211/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/215/100/100',
    title: '곱셈표 완성하기',
    point: 350,
    targetJob: 'DEVELOPER',
    questionCount: 10,
  },
  {
    projectId: 10,
    logoImageUrl: 'https://picsum.photos/id/232/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/202/100/100',
    title: '기초 과학 실험 도구 익히기',
    point: 270,
    targetJob: 'DEVELOPER',
    questionCount: 8,
  },
  {
    projectId: 11,
    logoImageUrl: 'https://picsum.photos/id/233/200/300',
    thumbnailImageUrl: 'https://picsum.photos/id/247/100/100',
    title: '한글 맞춤법 퀴즈',
    point: 380,
    targetJob: 'DEVELOPER',
    questionCount: 14,
  },
];
