import { PostCardItemSchema } from '@/types/schema';

export const fakePostCardItems: PostCardItemSchema[] = [
  {
    id: 1,
    imageUrl: 'https://picsum.photos/id/237/200/300',
    thumbnailUrl: 'https://picsum.photos/id/217/100/100',
    title: '초등학교 1학년 덧셈과 뺄셈 문제',
    point: 250,
    target: '초등 1학년',
    questionCount: 8,
    role: 'all',
  },
  {
    id: 2,
    imageUrl: 'https://picsum.photos/id/238/200/300',
    thumbnailUrl: 'https://picsum.photos/id/218/100/100',
    title: '영어 알파벳 대소문자 구별하기 글자수를 넘어가는지 테스트 테스트',
    point: 200,
    target: '유치원',
    questionCount: 12,
    role: 'designer',
  },
  {
    id: 3,
    imageUrl: 'https://picsum.photos/id/239/200/300',
    thumbnailUrl: 'https://picsum.photos/id/219/100/100',
    title: '기초 한자 퀴즈 - 숫자편',
    point: 350,
    target: '초등 전체',
    questionCount: 10,
    role: 'planner',
  },
  {
    id: 4,
    imageUrl: 'https://picsum.photos/id/240/200/300',
    thumbnailUrl: 'https://picsum.photos/id/240/100/100',
    title: '과학 실험 안전수칙 배우기',
    point: 200,
    target: '초등 3-4학년',
    questionCount: 6,
    role: 'developer',
  },
  {
    id: 5,
    imageUrl: 'https://picsum.photos/id/241/200/300',
    thumbnailUrl: 'https://picsum.photos/id/241/100/100',
    title: '동물의 생태계 이해하기',
    point: 400,
    target: '초등 5-6학년',
    questionCount: 15,
    role: 'all',
  },
  {
    id: 6,
    imageUrl: 'https://picsum.photos/id/242/200/300',
    thumbnailUrl: 'https://picsum.photos/id/242/100/100',
    title: '기초 음악 기호 알아보기',
    point: 280,
    target: '초등 2학년',
    questionCount: 9,
    role: 'all',
  },
  {
    id: 7,
    imageUrl: 'https://picsum.photos/id/243/200/300',
    thumbnailUrl: 'https://picsum.photos/id/243/100/100',
    title: '우리나라 지도 퍼즐',
    point: 320,
    target: '초등 3학년',
    questionCount: 8,
    role: 'developer',
  },
  {
    id: 8,
    imageUrl: 'https://picsum.photos/id/244/200/300',
    thumbnailUrl: 'https://picsum.photos/id/244/100/100',
    title: '기초 영단어 맞추기',
    point: 300,
    target: '초등 1-2학년',
    questionCount: 12,
    role: 'all',
  },
  {
    id: 9,
    imageUrl: 'https://picsum.photos/id/211/200/300',
    thumbnailUrl: 'https://picsum.photos/id/215/100/100',
    title: '곱셈표 완성하기',
    point: 350,
    target: '초등 2-3학년',
    questionCount: 10,
    role: 'developer',
  },
  {
    id: 10,
    imageUrl: 'https://picsum.photos/id/232/200/300',
    thumbnailUrl: 'https://picsum.photos/id/202/100/100',
    title: '기초 과학 실험 도구 익히기',
    point: 270,
    target: '초등 3-4학년',
    questionCount: 8,
    role: 'developer',
  },
  {
    id: 11,
    imageUrl: 'https://picsum.photos/id/233/200/300',
    thumbnailUrl: 'https://picsum.photos/id/247/100/100',
    title: '한글 맞춤법 퀴즈',
    point: 380,
    target: '초등 4-5학년',
    questionCount: 14,
    role: 'developer',
  },
];
